### ISSUE TITLE
how to use the cosy-airsim in my own projects building in different version of ue engine

### ISSUE THREAD

**Issue by TerryDonneyyds** [Cosys-Lab/Cosys-AirSim#2]
this is my issue:
i built a project in version 4.26 of ue engine, and i  followed the guide step by step to use the cosy-airsim in this project,but when i debug the .sln file,it showed the error like this 
The map failed to load! "C:/Users/15159/Documents/Unreal Projects/RealtimeArchvizAssetPack/Content/Bistrot/Bistrot.umap" is a Unreal Engine 4 map [File:v522] from a more recent engine version than the one being used currently [Cur:v518].

**Comment by WouterJansen** [comment]
I do not believe Unreal supports full-forward porting. So any Unreal file or asset made in a newer version of Unreal is not directly importable to our current version of Unreal based on 4.24. I think simpler assets like models and textures can be easily imported but files like blueprints and levels cannot.
