### ISSUE TITLE
raise error C2220 when I run build.cmd from the command line. 

### ISSUE THREAD

**Issue by hollywuzh** [Cosys-Lab/Cosys-AirSim#22]
I followed the guide (https://cosys-lab.github.io/install_windows/) and tried to build Cosys-AirSim. 
In the step "Run build.cmd from the command line". The command prompt raise error as blow. 
![image](https://github.com/user-attachments/assets/1d38740e-3657-49b4-adbb-7181948587f7)
The similar sceniro can be found in (https://github.com/Microsoft/AirSim/issues/76). However, I check the encoding of "Half.h" and it has no problem. So how can I solve this problem? Thanks.

**Comment by WouterJansen** [comment]
Can you try to re-save _Half.h_ as UTF-8 with BOM and try to compile again? I know Notepad++ can easily do this: 
![image](https://github.com/user-attachments/assets/122ae16f-9d38-4c5c-9a39-66ed6ad49106)

**Comment by hollywuzh** [comment]
The problem has been solved. I re-save Half.h\BFloat16.h\GenericPacketMathFunctions.h as UTF-8 with BOM in VSCode. Thanks!
