### ISSUE TITLE
slow image capturing

### ISSUE THREAD

**Issue by reza-shahriari** [Cosys-Lab/Cosys-AirSim#25]
Can we make the image capture process run faster? It is sequential instead of parallel especially when you capture two images instead of one image, fps get lower and lower!
the environment has many objects and features running in real-time, but when you start getting the image it's slow!
I have a really strong computer, the airsim is not using all of my resources. I mean too many CPU cores and a lot of GPU are not in use but the process is slow!
it will be nice if you help me change it to a faster way, if you can't implement it yourself just tell me the roadmap, and ill try to do it myself.
thanks for your nice work :)
 
 I know I can use noDisplay or turn off windows or even smaller images and then it will be faster but i want to solve the problem not just work with it 
 the main Airism Repo has this problem too, it's not the cosys-airsim problem.
 
  would running `std::vector<ImageCaptureBase::ImageRequest> request{
        ImageCaptureBase::ImageRequest(camera_details.camera_name, image_type, false, true, annotation_name)
    }; ` in a game thread (`UAirBlueprintLib::RunCommandOnGameThread`) help or not

**Comment by WouterJansen** [comment]
https://github.com/microsoft/AirSim/pull/3018
https://github.com/microsoft/AirSim/issues/4101

It is a known issue that GPU/CPU memory transfer and sequential image rendering are slow in (Cosys-)AirSim/Colloseum.

There are a few things that have been tried without success but there does not seem to be a magic thing that can be done to make it faster, unfortunately.

**Comment by reza-shahriari** [comment]
Thank you for your answer. after asking the questions I have searched a bit and i have found that someone used `FRHIGPUTextureReadback` and said it's faster for this task... i will try it and share the results.

**Comment by reza-shahriari** [comment]
I have tested some other capturing methods such as Streaming cameras but nothing worked as I wanted!
I think simplifying the environment lights, shadows, etc. would be the best way here
