### ISSUE TITLE
Adding drone issue (with Python Client)

### ISSUE THREAD

**Issue by vincentho7** [Cosys-Lab/Cosys-AirSim#38]
Hi,

I have some issue with adding drones on the environment. When i am running the script "add_drone.py", I get an error : 

```Exception thrown at 0x00007FFC54318DEF (UnrealEditor-Renderer.dll) in UnrealEditor-Win64-DebugGame.exe: 0xC0000005: Access violation reading location 0x00000831FBDC8A38.```

My version of Unreal Engine is 5.2.1, hello_drone.py works well

There were errors also in the file i changed the quaternion to :  airsim.Quaternionr(0, 0, 0, 0)

I am currently working with a free environment called Cityparkenvironement

**Comment by WouterJansen** [comment]
Hi, I could unfortunately not replicate this issue. I had to also fix the Quaternion definition to `airsim.Quaternionr(0, 0, 0, 0)`
as you did but did not get a crash in the Blocks environment. If you have any more logs or traces that would help to track down the issue. 

I used the following settings to start with:
```json
{
    "SeeDocsAt": "https://cosys-lab.github.io/settings/",
    "SettingsVersion": 2,
    "ClockSpeed": 1,
    "LocalHostIp": "127.0.0.1",
    "ApiServerPort": 41451,
    "RpcEnabled": true,
    "SimMode": "Multirotor",
    "Vehicles": {
        "Drone1": {
            "VehicleType": "SimpleFlight",
            "AllowAPIAlways": true,
            "X": 0,
            "Y": 0,
            "Z": 0,
            "Yaw": 0
        }
    }
}
```
