### ISSUE TITLE
MaterialList.cvs Missing?

### ISSUE THREAD

**Issue by samynjonas** [Cosys-Lab/Cosys-AirSim#4]
When I launch a Unreal Engine project with the Cosys-Airsim plugin and I try to run it, but it does give an error that the MaterialList.csv is  missing, I suppose it should be generated together with the settings.json but that does work

PROBLEM:
MaterialList.csv doesn't get generated

**Comment by WHaLe2400** [comment]
may I ask how you dealed with this issue. I'm having the same problem. Not knowing how to solve thsi
