### ISSUE TITLE
Adding Intensity field for LiDAR

### ISSUE THREAD

**Issue by Robotgir** [Cosys-Lab/Cosys-AirSim#46]
Hi @WouterJansen wouldnt it be useful to add intensity field to Lidar and GPUlidar sensors as every modern Lidar has this filed and most of the SLAM packages ask for this field to use them.

In #31 already mentioned that it would require refactoring of Cosys-airsim code. Can you give me directions to look at i would like to contribute here.

Thanks!

**Comment by WouterJansen** [comment]
The GPULIDAR sensor in Cosys-AirSim does implement a simulation abstraction of intensity by implementing material reflectivity and the impact angle of the LiDAR signals. You can find some more info here in the documentation: https://cosys-lab.github.io/gpulidar/

Please see the paper about this here for more technical information about the implementation: https://arxiv.org/abs/2208.10295
